Update README.md
marichain/javascriptStyleGuide pull request #1
Opened 2018-10-03 18:49 UTC by shaunluttin

2018-10-11 21:35 UTC, thisissami requested changes

2018-10-11 21:35 UTC, thisissami commented on README.md
> +    import { Foo } from '..';
this should be from `.`;

2018-10-11 21:35 UTC, thisissami commented
feel free to merge in after you address that one thing

2018-10-11 21:39 UTC, thisissami commented
One more thing @shaunluttin - could you add a link to your testing README from the main README? if you scroll down a tiny bit, you'll see some links to `react-testing`, `css-in-js`, etc. - it would be really useful to have the link to your new testing doc there too.

2018-10-11 21:39 UTC, thisissami commented
also is it possible to add colors to that chart that you created for testing?

2018-10-17 23:25 UTC, shaunluttin commented
> also is it possible to add colors to that chart that you created for testing?

It would be possible if we used an image; as far as I can tell, though, markdown in GitHub does not support colors. https://guides.github.com/features/mastering-markdown/

@thisissami 

P.S. And images have a downside of not being searchable.

2018-10-17 23:31 UTC, merged